CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE CHECK (length(username) BETWEEN 1 AND 100),
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    token_version BIGINT NOT NULL DEFAULT 0 CHECK (token_version BETWEEN 0 AND 9007199254740991),
    oauth_provider VARCHAR(100),
    oauth_subject VARCHAR(255),
    last_login_at TIMESTAMP,
    address_book_version BIGINT NOT NULL DEFAULT 0 CHECK (address_book_version BETWEEN 0 AND 9007199254740991),
    failed_login_count BIGINT NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
    locked_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (id BETWEEN 1 AND 9007199254740991)
);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_oauth ON users(oauth_provider, oauth_subject);
CREATE INDEX idx_users_last_login_at ON users(last_login_at);
CREATE INDEX idx_users_token_version ON users(token_version);
CREATE INDEX idx_users_locked_until ON users(locked_until) WHERE locked_until IS NOT NULL;

CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    parent_group_id BIGINT REFERENCES groups(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_groups_owner_user_id ON groups(owner_user_id);
CREATE INDEX idx_groups_parent_group_id ON groups(parent_group_id);
CREATE INDEX idx_groups_owner_parent_id ON groups(owner_user_id, parent_group_id, id);

CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid BYTEA NOT NULL UNIQUE,
    uuid BYTEA NOT NULL,
    pk BYTEA NOT NULL,
    device_id VARCHAR(100) NOT NULL UNIQUE,
    owner_user_id BIGINT REFERENCES users(id),
    group_id BIGINT REFERENCES groups(id),
    device_name VARCHAR(200),
    os VARCHAR(100),
    note VARCHAR(300),
    info TEXT NOT NULL,
    features TEXT,
    token_version BIGINT NOT NULL DEFAULT 0,
    is_online BOOLEAN NOT NULL DEFAULT FALSE,
    last_online_at TIMESTAMP,
    status TEXT NOT NULL DEFAULT 'offline' CHECK (status IN ('online', 'offline', 'inactive')),
    last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alias TEXT,
    management_generation TEXT NOT NULL DEFAULT replace(gen_random_uuid()::text, '-', '')
        CHECK (management_generation ~ '^[0-9a-f]{32}$'),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(id, management_generation, device_id)
);
CREATE INDEX idx_devices_owner_user_id ON devices(owner_user_id);
CREATE INDEX idx_devices_group_id ON devices(group_id);
CREATE INDEX idx_devices_created_at ON devices(created_at);
CREATE INDEX idx_devices_status_last_seen ON devices(status, last_seen);
CREATE INDEX idx_devices_owner_group_id ON devices(owner_user_id, group_id, id);
CREATE INDEX idx_devices_owner_status_id ON devices(owner_user_id, status, id);

CREATE TABLE licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES users(id),
    device_limit INTEGER NOT NULL DEFAULT 5,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    features TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_licenses_user_id ON licenses(user_id);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(50),
    resource_id VARCHAR(255),
    detail TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX idx_audit_logs_resource_created_at ON audit_logs(resource_type, created_at DESC);
CREATE INDEX idx_audit_logs_user_created_at ON audit_logs(user_id, created_at DESC);
CREATE INDEX idx_audit_logs_action_created_at ON audit_logs(action, created_at DESC);

CREATE TABLE device_quota_lock (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    version BIGINT NOT NULL DEFAULT 0
);
INSERT INTO device_quota_lock(id, version) VALUES(1, 0);

CREATE TABLE inventory_write_lock (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    version BIGINT NOT NULL DEFAULT 0
);
INSERT INTO inventory_write_lock(id, version) VALUES(1, 0);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    name TEXT NOT NULL CHECK (name = trim(name) AND length(name) BETWEEN 1 AND 64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX idx_tags_owner_name ON tags(owner_user_id, lower(name));

CREATE TABLE device_tags (
    device_row_id BIGINT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(device_row_id, tag_id)
);
CREATE INDEX idx_device_tags_tag_device ON device_tags(tag_id, device_row_id);

CREATE TABLE device_deletion_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL REFERENCES users(id),
    device_id TEXT NOT NULL,
    management_generation TEXT NOT NULL CHECK (management_generation ~ '^[0-9a-f]{32}$'),
    deleted_guid BYTEA NOT NULL CHECK (octet_length(deleted_guid) = 16),
    state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'completed')),
    attempt_count BIGINT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_token TEXT,
    lease_until TIMESTAMP,
    completed_at TIMESTAMP,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(actor_user_id, device_id, management_generation)
);
CREATE INDEX idx_device_deletion_outbox_due ON device_deletion_outbox(state, next_attempt_at, id);
CREATE INDEX idx_device_deletion_outbox_expiry ON device_deletion_outbox(expires_at, id);

CREATE TABLE device_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id BETWEEN 1 AND 9007199254740991),
    device_row_id BIGINT NOT NULL,
    device_lifecycle TEXT NOT NULL CHECK (device_lifecycle ~ '^[0-9a-f]{32}$'),
    device_id TEXT NOT NULL CHECK (length(device_id) BETWEEN 1 AND 100),
    from_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    to_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission TEXT NOT NULL CHECK (permission IN ('view_only', 'full_control')),
    status TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'rejected')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(device_row_id, to_user_id),
    CHECK(from_user_id <> to_user_id),
    FOREIGN KEY(device_row_id, device_lifecycle, device_id)
        REFERENCES devices(id, management_generation, device_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX idx_device_shares_recipient_status_id ON device_shares(to_user_id, status, id);
CREATE INDEX idx_device_shares_owner_device_status ON device_shares(from_user_id, device_row_id, status);
CREATE INDEX idx_device_shares_device_recipient ON device_shares(device_id, to_user_id);

CREATE TABLE address_book_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    version BIGINT NOT NULL CHECK (version BETWEEN 1 AND 9007199254740991),
    device_row_id BIGINT REFERENCES devices(id) ON DELETE SET NULL,
    device_lifecycle TEXT NOT NULL CHECK (device_lifecycle ~ '^[0-9a-f]{32}$'),
    device_id TEXT NOT NULL CHECK (length(device_id) BETWEEN 1 AND 100),
    share_id BIGINT CHECK (share_id IS NULL OR share_id BETWEEN 1 AND 9007199254740991),
    operation TEXT NOT NULL CHECK (operation IN ('upsert', 'delete')),
    payload TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, version),
    CHECK ((operation = 'upsert' AND payload IS NOT NULL) OR (operation = 'delete' AND payload IS NULL))
);
CREATE INDEX idx_ab_changes_user_lifecycle_version ON address_book_changes(user_id, device_lifecycle, version DESC);

CREATE TABLE address_book_backfill_state (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    completed BIGINT NOT NULL DEFAULT 0 CHECK (completed IN (0, 1))
);
INSERT INTO address_book_backfill_state(id, completed) VALUES(1, 0);

CREATE TABLE security_policies (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    password_min_length BIGINT NOT NULL CHECK (password_min_length BETWEEN 1 AND 1024),
    password_require_number BOOLEAN NOT NULL,
    password_require_symbol BOOLEAN NOT NULL,
    login_max_failures BIGINT NOT NULL CHECK (login_max_failures BETWEEN 1 AND 100),
    login_lock_minutes BIGINT NOT NULL CHECK (login_lock_minutes BETWEEN 1 AND 10080),
    session_timeout_minutes BIGINT NOT NULL CHECK (session_timeout_minutes BETWEEN 1 AND 525600),
    allowed_admin_cidrs TEXT NOT NULL CHECK (jsonb_typeof(allowed_admin_cidrs::jsonb) = 'array'),
    audit_retention_days BIGINT NOT NULL CHECK (audit_retention_days BETWEEN 1 AND 3650),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE FUNCTION rustdesk_validate_group() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    ancestor_depth INTEGER := 0;
    subtree_depth INTEGER := 1;
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.owner_user_id <> OLD.owner_user_id THEN
        RAISE EXCEPTION 'group_owner_immutable';
    END IF;
    IF NEW.parent_group_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM groups WHERE id = NEW.parent_group_id AND owner_user_id = NEW.owner_user_id
    ) THEN
        RAISE EXCEPTION 'group_parent_owner_mismatch';
    END IF;
    IF NEW.parent_group_id = NEW.id OR (NEW.parent_group_id IS NOT NULL AND EXISTS (
        WITH RECURSIVE ancestors(id, depth) AS (
            SELECT NEW.parent_group_id, 1
            UNION ALL
            SELECT parent.parent_group_id, ancestors.depth + 1
            FROM groups parent JOIN ancestors ON parent.id = ancestors.id
            WHERE parent.parent_group_id IS NOT NULL AND ancestors.depth <= 256
        )
        SELECT 1 FROM ancestors WHERE id = NEW.id
    )) THEN
        RAISE EXCEPTION 'group_cycle';
    END IF;
    IF NEW.parent_group_id IS NOT NULL THEN
        WITH RECURSIVE ancestors(id, depth) AS (
            SELECT NEW.parent_group_id, 1
            UNION ALL
            SELECT parent.parent_group_id, ancestors.depth + 1
            FROM groups parent JOIN ancestors ON parent.id = ancestors.id
            WHERE parent.parent_group_id IS NOT NULL AND ancestors.depth <= 256
        )
        SELECT COALESCE(MAX(depth), 0) INTO ancestor_depth FROM ancestors;
    END IF;
    IF TG_OP = 'UPDATE' THEN
        WITH RECURSIVE descendants(id, depth) AS (
            SELECT NEW.id, 1
            UNION ALL
            SELECT child.id, descendants.depth + 1
            FROM groups child JOIN descendants ON child.parent_group_id = descendants.id
            WHERE descendants.depth <= 256
        )
        SELECT COALESCE(MAX(depth), 1) INTO subtree_depth FROM descendants;
    END IF;
    IF ancestor_depth + subtree_depth > 256 THEN
        RAISE EXCEPTION 'group_depth_exceeded';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER group_integrity BEFORE INSERT OR UPDATE ON groups
FOR EACH ROW EXECUTE FUNCTION rustdesk_validate_group();

CREATE FUNCTION rustdesk_validate_device() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.management_generation IS NOT NULL
       AND NEW.management_generation <> OLD.management_generation THEN
        RAISE EXCEPTION 'device_management_generation_immutable';
    END IF;
    IF NEW.group_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM groups WHERE id = NEW.group_id AND owner_user_id = NEW.owner_user_id
    ) THEN
        RAISE EXCEPTION 'device_group_owner_mismatch';
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.owner_user_id IS DISTINCT FROM OLD.owner_user_id
       AND EXISTS (SELECT 1 FROM device_tags WHERE device_row_id = OLD.id) THEN
        RAISE EXCEPTION 'device_owner_change_with_tags';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER device_integrity BEFORE INSERT OR UPDATE ON devices
FOR EACH ROW EXECUTE FUNCTION rustdesk_validate_device();

CREATE FUNCTION rustdesk_validate_tag() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.owner_user_id <> OLD.owner_user_id THEN
        RAISE EXCEPTION 'tag_owner_immutable';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER tag_integrity BEFORE UPDATE ON tags
FOR EACH ROW EXECUTE FUNCTION rustdesk_validate_tag();

CREATE FUNCTION rustdesk_validate_device_tag() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM devices d JOIN tags t ON t.id = NEW.tag_id
        WHERE d.id = NEW.device_row_id AND d.owner_user_id IS NOT NULL
          AND d.owner_user_id = t.owner_user_id
    ) THEN
        RAISE EXCEPTION 'device_tag_owner_mismatch';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER device_tag_integrity BEFORE INSERT OR UPDATE ON device_tags
FOR EACH ROW EXECUTE FUNCTION rustdesk_validate_device_tag();

CREATE FUNCTION rustdesk_validate_share() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM devices WHERE id = NEW.device_row_id
          AND management_generation = NEW.device_lifecycle
          AND device_id = NEW.device_id AND owner_user_id = NEW.from_user_id
    ) THEN
        RAISE EXCEPTION 'device_share_owner_mismatch';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER device_share_integrity BEFORE INSERT OR UPDATE ON device_shares
FOR EACH ROW EXECUTE FUNCTION rustdesk_validate_share();

CREATE FUNCTION rustdesk_validate_address_book_change() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE previous_version BIGINT;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'address_book_change_immutable';
    END IF;
    SELECT COALESCE(MAX(version), 0) INTO previous_version
      FROM address_book_changes WHERE user_id = NEW.user_id;
    IF previous_version <> NEW.version - 1 OR NOT EXISTS (
        SELECT 1 FROM users WHERE id = NEW.user_id AND address_book_version = NEW.version
    ) THEN
        RAISE EXCEPTION 'address_book_change_not_contiguous';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER address_book_change_insert_valid BEFORE INSERT ON address_book_changes
FOR EACH ROW EXECUTE FUNCTION rustdesk_validate_address_book_change();
CREATE TRIGGER address_book_change_immutable BEFORE UPDATE OR DELETE ON address_book_changes
FOR EACH ROW EXECUTE FUNCTION rustdesk_validate_address_book_change();
